name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint_test_coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12, 3.13]

    steps:
      # 1) checkout your code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) install Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # 3) cache pip for speed
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4) install your requirements + dev tools
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5) lint & format via your pre-commit hooks
      - name: Run pre-commit hooks
        run: pre-commit run --all-files

      # 6) run pytest & generate coverage.xml
      - name: Test with pytest
        run: |
          pytest tests/ \
            --maxfail=1 --disable-warnings -q \
            --cov=src --cov-report=xml

      # 7) upload coverage to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          # slug can be omitted; Codecov Action infers it automatically
